#!/bin/sh

./gophermarttest \
    -test.v -test.run=^TestGophermart$ \
    -gophermart-binary-path=../cmd/gophermart/gophermart \
    -gophermart-host=localhost \
    -gophermart-port=8088 \
    -gophermart-database-uri="postgres://gophermart:gophermart@localhost:5432/gophermart?sslmode=disable" \
    -accrual-binary-path=../cmd/accrual/accrual_linux_amd64 \
    -accrual-host=localhost \
    -accrual-port=8080 \
    -accrual-database-uri="postgres://accrual:accrual@localhost:6432/gophermart?sslmode=disable"
